export const serviceAreas = [
  {
    id: "dev",
    label: "Custom Development",
    icon: "solar:code-bold",
    headline: "Web & mobile apps built for scale.",
    desc: "Full-stack engineering from MVP to enterprise – React, Node, Python, mobile, and APIs tailored to your roadmap.",
    spec: "TypeScript · React · Node · PostgreSQL",
  },
  {
    id: "cloud",
    label: "Cloud & DevOps",
    icon: "solar:cloud-bold",
    headline: "Infrastructure that ships reliably.",
    desc: "AWS, Azure, and GCP – CI/CD, Kubernetes, monitoring, and cost optimization from day one.",
    spec: "AWS · Terraform · Kubernetes",
  },
  {
    id: "design",
    label: "UI/UX Design",
    icon: "solar:palette-bold",
    headline: "Interfaces users actually love.",
    desc: "Research, wireframes, design systems, and pixel-perfect handoff – product design as a discipline.",
    spec: "Figma · Design systems · A11y",
  },
  {
    id: "ai",
    label: "AI & Data",
    icon: "solar:magic-stick-bold",
    headline: "Intelligent products, responsibly built.",
    desc: "LLM integrations, data pipelines, analytics dashboards, and ML features with guardrails built in.",
    spec: "OpenAI · LangChain · Vector DBs",
  },
  {
    id: "mobile",
    label: "Mobile Development",
    icon: "solar:smartphone-bold",
    headline: "Native-quality apps on every platform.",
    desc: "iOS, Android, and cross-platform builds – offline sync, push notifications, and app store release support.",
    spec: "React Native · iOS · Android",
  },
  {
    id: "qa",
    label: "QA & Automation",
    icon: "solar:test-tube-bold",
    headline: "Quality built into every release.",
    desc: "Test strategy, automated suites, performance testing, and release gates that keep production stable.",
    spec: "Playwright · Cypress · k6",
  },
  {
    id: "data",
    label: "Data Engineering",
    icon: "solar:database-bold",
    headline: "Pipelines that power decisions.",
    desc: "ETL/ELT, warehousing, real-time streaming, and BI dashboards – clean data your teams can trust.",
    spec: "dbt · Snowflake · Airflow",
  },
  {
    id: "consulting",
    label: "Product Strategy",
    icon: "solar:clipboard-list-bold",
    headline: "Clarity before you write code.",
    desc: "Discovery workshops, technical due diligence, architecture reviews, and roadmaps aligned to business outcomes.",
    spec: "Discovery · Roadmaps · Architecture",
  },
  {
    id: "it-consulting",
    label: "Consulting",
    icon: "solar:hand-shake-bold",
    headline: "Expert guidance when stakes are high.",
    desc: "IT strategy, digital transformation, vendor selection, and technical advisory for leadership teams making big bets.",
    spec: "Strategy · Transformation · Advisory",
  },
  {
    id: "security",
    label: "Security & Compliance",
    icon: "solar:shield-check-bold",
    headline: "Secure by design, audit-ready.",
    desc: "Secure SDLC, penetration testing coordination, and HIPAA/SOC 2-aligned practices for regulated industries.",
    spec: "SOC 2 · HIPAA · OWASP",
  },
  {
    id: "maintenance",
    label: "Maintenance",
    icon: "solar:restart-bold",
    headline: "Keep systems healthy after launch.",
    desc: "Bug fixes, dependency updates, security patches, and performance tuning for apps already in production.",
    spec: "Patches · Upgrades · Bug fixes",
  },
  {
    id: "managed",
    label: "Managed Services",
    icon: "solar:settings-bold",
    headline: "Ops support that scales with you.",
    desc: "24/7 monitoring, incident response, cloud ops, and feature development on retainer – we run it so you don't have to.",
    spec: "24/7 monitoring · SLAs",
  },
] as const;

export const enterpriseMatrix = [
  {
    capability: "Team composition",
    legacy: "Freelancer patchwork",
    withTek4Real: "Senior cross-functional squad",
  },
  { capability: "Time to start", legacy: "2–3 months hiring", withTek4Real: "2 weeks to kickoff" },
  {
    capability: "Code quality",
    legacy: "Inconsistent standards",
    withTek4Real: "Reviewed, tested, documented",
  },
  {
    capability: "Design & dev alignment",
    legacy: "Separate handoffs",
    withTek4Real: "Unified workflow",
  },
  {
    capability: "Post-launch support",
    legacy: "None or ad-hoc",
    withTek4Real: "Retainer & SLA options",
  },
  {
    capability: "Security practices",
    legacy: "Varies by contractor",
    withTek4Real: "SOC 2-aligned SDLC",
  },
  {
    capability: "Scalability",
    legacy: "Short-term fixes",
    withTek4Real: "Architecture for growth",
  },
] as const;
